"""Add audit log table

Revision ID: 3d4dc6ec3775
Revises: 5db7aa41dd6c
Create Date: 2025-06-24 10:42:12.943581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4dc6ec3775'
down_revision: Union[str, Sequence[str], None] = '5db7aa41dd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_date', table_name='attendance')
    op.drop_index('ix_attendance_id', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_positions_id', table_name='positions')
    op.drop_index('ix_positions_title', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_payroll_id', table_name='payroll')
    op.drop_table('payroll')
    op.drop_index('ix_leave_requests_id', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index('ix_employees_employee_id', table_name='employees')
    op.drop_index('ix_employees_first_name', table_name='employees')
    op.drop_index('ix_employees_id', table_name='employees')
    op.drop_index('ix_employees_last_name', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_departments_id', table_name='departments')
    op.drop_index('ix_departments_name', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('head_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_departments_name', 'departments', ['name'], unique=1)
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('hire_date', sa.DATE(), nullable=True),
    sa.Column('employment_status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('position_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.Column('salary', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_employees_last_name', 'employees', ['last_name'], unique=False)
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    op.create_index('ix_employees_first_name', 'employees', ['first_name'], unique=False)
    op.create_index('ix_employees_employee_id', 'employees', ['employee_id'], unique=1)
    op.create_table('leave_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('leave_type', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('days_requested', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('approved_by', sa.INTEGER(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_requests_id', 'leave_requests', ['id'], unique=False)
    op.create_table('payroll',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('pay_period_start', sa.DATE(), nullable=True),
    sa.Column('pay_period_end', sa.DATE(), nullable=True),
    sa.Column('gross_salary', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('deductions', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('net_salary', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('tax_deduction', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payroll_id', 'payroll', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('positions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('min_salary', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('max_salary', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_title', 'positions', ['title'], unique=False)
    op.create_index('ix_positions_id', 'positions', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('clock_in', sa.DATETIME(), nullable=True),
    sa.Column('clock_out', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_id', 'attendance', ['id'], unique=False)
    op.create_index('ix_attendance_date', 'attendance', ['date'], unique=False)
    # ### end Alembic commands ###
